<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Backend/Modules/TicketBooking.Identity.Core/TicketBooking.Identity.Core.csproj" />
    </ItemGroup>

</Project>
