// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketBooking.Identity.Internal.Persistence;

#nullable disable

namespace TicketBooking.Identity.Core.Internal.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketBooking.Identity.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Name");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("Version");

                    b.HasKey("Id")
                        .HasName("PK_Permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Permissions_Code");

                    b.ToTable("Permissions", "identity");
                });

            modelBuilder.Entity("TicketBooking.Identity.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Name");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("Version");

                    b.HasKey("Id")
                        .HasName("PK_Roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_Code");

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("TicketBooking.Identity.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("RoleId");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("PermissionId");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("PK_RolePermissions");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("UX_RolePermissions_RoleId_PermissionId");

                    b.ToTable("RolePermissions", "identity");
                });

            modelBuilder.Entity("TicketBooking.Identity.Domain.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("Email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("FailedLoginAttempts");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("FirstName");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastLoginAt");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("LastName");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Login");

                    b.Property<string>("NormalizedLogin")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NormalizedLogin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("UpdatedBy");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("Version");

                    b.HasKey("Id")
                        .HasName("PK_SystemUsers");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_SystemUsers_Email");

                    b.HasIndex("NormalizedLogin")
                        .IsUnique()
                        .HasDatabaseName("UX_SystemUsers_NormalizedLogin");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SystemUsers_Status");

                    b.ToTable("SystemUsers", "identity");
                });

            modelBuilder.Entity("TicketBooking.Identity.Domain.SystemUserRole", b =>
                {
                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("SystemUserId");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("RoleId");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AssignedAt");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("AssignedBy");

                    b.HasKey("SystemUserId", "RoleId")
                        .HasName("PK_SystemUserRoles");

                    b.HasIndex("RoleId");

                    b.HasIndex("SystemUserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UX_SystemUserRoles_SystemUserId_RoleId");

                    b.ToTable("SystemUserRoles", "identity");
                });

            modelBuilder.Entity("TicketBooking.Identity.Domain.RolePermission", b =>
                {
                    b.HasOne("TicketBooking.Identity.Domain.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Permissions_PermissionId");

                    b.HasOne("TicketBooking.Identity.Domain.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Roles_RoleId");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TicketBooking.Identity.Domain.SystemUserRole", b =>
                {
                    b.HasOne("TicketBooking.Identity.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SystemUserRoles_Roles_RoleId");

                    b.HasOne("TicketBooking.Identity.Domain.SystemUser", "SystemUser")
                        .WithMany("Roles")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SystemUserRoles_SystemUsers_SystemUserId");

                    b.Navigation("Role");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("TicketBooking.Identity.Domain.Permission", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("TicketBooking.Identity.Domain.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("TicketBooking.Identity.Domain.SystemUser", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
